### ISSUE TITLE
Coefficients for Large N values

### ISSUE THREAD

**Issue by anene** [rdireen/spherepy#5]
High N values (>~1200) produce large coefficient values that seem odd (>10^64+)

**Comment by rdireen** [comment]
This sounds like it could possibly be a Gibbs ringing problem. This happens when you don't have the data in quite right. Discontinuities will cause ringing in higher n values. Instructions for formatting the data can be found [here](http://www.direentech.com/docs/spherepy/Details.html#scalar-case) under the ScalarPatternUniform section. But, if you send me your data file I'll put it in correctly for ya.

Could you post the code you used to import the data with?

**Comment by rdireen** [comment]
@anene I've confirmed that this is actually a bug within the lower level routine of spherepy. In pysphi/csphi there is a routine called ynnm that has a loop that underflows. I'll get to this soon.

**Comment by rdireen** [comment]
I have fixed the dynamic range issues in pysphi and csphi. The Fourier coefficients ynunm generated by recursion formulas had underflow and overflow problems. I fixed the problem by dynamically changing the range with an extended exponent as I recursed through the values, and when I had a full vector of Fourier coefficients I adjusted their values with that extended exponent.
